### ISSUE TITLE
USER-STORY: Like recipes

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#13]
* As a **Registered Site User**, I can **like recipes**, so that **I can show I liked a particular recipe**.

## Acceptance Criteria:
* The user can click on the like button to like a recipe.
* The user won’t be able to like recipes unless they are registered.
* The user will be able to see on screen how many likes a recipe has.

## Tasks:
- [x] Update the recipe model to add likes.
- [x] Create the view to control the recipes likes.
- [x] Add a like button to the recipeUnit template.

**Comment by leonardo-simeone** [comment]
* Loaded TinyMCE to the site using cdn.tiny.cloud by adding the script to base template head.
* Register to Tiny cloud so I could get an API key.
* Added the API key to the script src.
* Added script with tinymce init and its features to base template head. 
* Added TINYMCE_JS_URL key to settings.py with cdn and its correspondent API key as its value.
* Registered local and deployed domains for the project in my TinyCloud account.
* Tested that TinyMCE was working properly on the front-end and the admin panel.
