### ISSUE TITLE
USER-STORY: Contact site administrator

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#14]
As a **Site User**, I can **contact the site administrator**, so that **I can query/recommend the site admin on different topics**

## Acceptance Criteria:
* The user can click on a contact link to a contact form. 
* The user can contact the site admin whether they're registered or not.
* The user will be able to see/read on screen a message confirming the action success.

## Tasks:
- [x] Create the contact model to build the contacts table in the database.
- [x] Create the form model to allow the user to contact site admin.
- [x] Create the view to control the contact process.
- [x] Create the contact template.
- [x] Update css to cater for the new contact template.

**Comment by leonardo-simeone** [comment]
* Created the contact model to build the contacts table in the database.
* Created the form model to allow the user to contact site admin.
* Created the view to control the contact process.
* Created the contact template.
* Updated css to cater for the new contact template.
* Updated README and TESTING files to include the newly created Contact model, form, url, view and their corresponding unit tests.
