### ISSUE TITLE
USER-STORY: View recipe list

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#3]
As a **Site User** I can **view a list of recipes** so that **I can select one to read**.

## Acceptance Criteria:
* The recipes are listed in the home page.
* The information listed for each recipe is limited to title, brief description, featured image and date created.
* The recipes should be displayed from newest to oldest

## Tasks:

- [ ] Create the view function and the template to list the recipes.
- [ ] Update the model to list corresponding recipes in descending order.
- [ ] Create the HTML and CSS necessary to display the content in a user-friendly way.

**Comment by leonardo-simeone** [comment]
* Created the recipes view.
* Created the urls.py for the cookbook app.
* Connected the project's main url to the app's url.
* Created the base template containing header and footer.
* Created the index template and extended base template to it.
* Added static images to be used in the index page.
* Using Bootstrap, created HTML and CSS necessary to display content.
* Further styled base and index pages although it's not the final styling yet.
* Updated Recipe model to order recipes in descending order.
