### ISSUE TITLE
USER-STORY: Create recipe as a registered user

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#6]
* As a **Site User** I can **register an account** so that **I can create my own recipes**.

## Acceptance Criteria:
* The user can register to the site by creating a user account.
* The user can login and logout of their account.
* Once logged in, the user can create their own recipes.

## Tasks:

- [x] Create the form model to allow the user to sing up and/or login.
- [x] Create the form model to allow the user to create new recipes.
- [x] Create the view to control the register new user, login and logout processes.
- [x] Create the view to control new recipe creation by registered user.
- [x] Create templates to display register and login forms.
- [x] Create template to display new recipe creation form.
- [x] Update the base template to allow only logged in users to create new recipes.

**Comment by leonardo-simeone** [comment]
* Created the loginView view which displays the login template.
* Connected the loginView to app urls.
* Created the login template.
* Logged in some created users to test functionality.
* Created logoutView view.
* Connected the logoutView to app urls.
* Tested logout functionality.
* Created the form model to create new recipe.
* Created the createRecipe view to control and display the recipe form.
* Updated and connected the base template to allow only logged in users to create recipes.
* Created a recipe to test functionality.
* Even though the tasks are in essence completed, I'm not closing the user story until I finish CSS optimization for the new recipe form.
* The layout and CSS up to this point for the whole project is not final, it is simply a bone structure to advance with the back-end tasks.

**Comment by leonardo-simeone** [comment]
* Completed the styling necessary to finish new recipe form.
* Adjusted createRecipe view to make sure the logged in user is in fact the one registered as the recipe creator.
* Added complementary CSS for the rest of the forms.
