### ISSUE TITLE
USER-STORY: Comment a recipe as a registered user

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#7]
* As a **Registered Site User**, I can **make comments on a recipe** so that **I can start and/or be involved in a conversation**.

## Acceptance Criteria:
* The user won’t be able to make comments on recipes unless registered.
* If the user is logged out, they’ll be able to see the comments but not participate in the conversation.
* Once logged in, the user can make comments on the recipes.

## Tasks:

- [x] Create the form model to allow the user to make comments on the recipes.
- [x] Create the view to control the process to make a comment.
- [x] Update the template to allow only logged in users to make comments on recipes.

**Comment by leonardo-simeone** [comment]
* Created the form model for comments, which contains body as its sole field.
* The other two fields necessary to satisfy the Comment model are taken from the User object for 'name' and the Recipe Object for 'recipe'.
* Updated the recipeUnit view to include the comment form in it, instead of coding a new view just for comments.
* Updated the recipe template to include the comment form and to allow only logged in users to make comments.
