### ISSUE TITLE
USER-STORY: Update and delete recipe

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#8]
* As a **Registered Site User**, I can **update and delete recipes** so that **I can manage my recipes content**.

## Acceptance Criteria:
* The user won’t be able to create, update or delete recipes unless registered.
* If the user is logged out, they’ll be able to see the recipes.
* Once logged in, the user can create, read, update and delete their recipes.

## Tasks:

- [ ] Update the recipe template to show the user the update and delete their recipe options.
- [ ] Create the views to control update and delete processes.
- [ ] Add the logic necessary to make sure that only the recipe owner can update it or delete it.

**Comment by leonardo-simeone** [comment]
* Updated the recipe template to show the correct user the options to update and delete their recipes.
* I made sure that if the logged in user is not the recipe owner/creator then they won't be able to update/delete it.
* I am currently coding the view to control the update process.

**Comment by leonardo-simeone** [comment]
* Created the update and delete views to control update and delete processes for registered users.
* Only under the conditional equals true for registered user and recipe owner will the user be able to update or delete a recipe.
* Added CSS and JS to improve UX in forms.
* Colors, layout and JS logic still require optimization which will be done once the back end functionality is fully working across the site.
