### ISSUE TITLE
USER-STORY: Place tags on recipe

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/venezuelan-food-cookbook#9]
* As a **Registered Site User**, I can **place tags on my created recipes** so that **I can indicate the meal type**.

## Acceptance Criteria:
* The user can select tags to place on their recipes.
* The tags are a selection option in the create/update recipe form.
* The user can select all, some or no tags on their recipes.
* The tags will be displayed in the individual recipe page.

## Tasks:
- [x] Create the tags field in the Recipe model.
- [x] Create the available options tuple for tags in model.py.
- [x] Create the available options tuple for tags in forms.py.
- [x] Update the RecipeForm model to add tags.
- [x] Update the individual recipe template to add the tags.

**Comment by leonardo-simeone** [comment]
* Created the tags field in the Recipe model. This field was originally planned to be a M2M field but I changed it to a MultiSelectField field instead.
* Downloaded the django-multiselectfield package.
* Added the django-multiselectfield package to INSTALLED_APPS in settings.py.
* Imported MultiSelectField to models.py.
* Created the available options tuple for tags in model.py.
* Created the available options tuple for tags in forms.py.
* Defined tags as a MultipleChoiceField with a widget = CheckboxSelectMultiple in forms.py.
* Updated the RecipeForm model to add tags.
* Updated the individual recipe template to add the tags.
* Tested the tags functionality.
